baseURL = "https://pkg.arnov.dev"
title = "Shae.Pkg"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "Arno / Shae"
authorimage = "../assets/images/global/icon-big.png"
github = "https://github.com/arnos-stuff"
og_image = "../assets/images/Topo-F.png"
sitename = "Arno's Packages"
twitter = "@arno_shae"
description = "My small package dedicated website"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"
posts = '/posts/:section/:title/'

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.104.0"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".png$", ".svg$", ".jpg$", ".gif$"]



[[deployment.targets]]
# An arbitrary name for this target.
name = "deploy"
include = ["**.{png,jpg,svg,html,js,css}", "assets/**/**.{png,jpg,svg,html,js,css}"]